### ISSUE TITLE
Max pooling

### ISSUE THREAD

**Issue by ahyunSeo** [mjq11302010044/RRPN_pytorch#13]
Hello,

In your paper the Algorithm 2 states that you do max pooling over a single region fro an inclined proposal to a point in the RROI. In the original caffe repo is implemented as max pooling.
https://github.com/mjq11302010044/RRPN/blob/8df1627e74f79db8be0467e08e3bdded63570fb5/caffe-fast-rcnn/src/caffe/layers/rotate_roi_pooling_layer.cu#L82
 

However when I took a look at the code in this repo, it seems like you do bilinear interpolation of 4 vertices for each subregions. Is there any other reason? My one guess is to make it comparable with the maskrcnn benchmark. Or did I miss some details? 

https://github.com/mjq11302010044/RRPN_pytorch/blob/master/maskrcnn_benchmark/csrc/cuda/RROIAlign_cuda.cu#L133

Best,

Ahyun

**Comment by mjq11302010044** [comment]
@ahyunSeo Yep, we change our max pooling to bilinear interpolation in RRoI Pool operation, which reports better performance in many detection tasks. You can see more detail in README.md

**Comment by ahyunSeo** [comment]
Oh I didn't see the part in the README.md. So basically you replaced RoIPool with RoIAlign. 
One more thing is, is there any other reason than simplicity you fixed the sampling ratio as 1? In RoIAlign they use 2x2 or more.

**Comment by mjq11302010044** [comment]
@ahyunSeo We have been discussed the differences in another issue. We don't mean to implement totally the same as RoI Align with a sampling ratio, we just change it to interpolation. You can re-implement the sampling ratio as RoI Align do. :)

**Comment by ahyunSeo** [comment]
OK thanks!
