### ISSUE TITLE
About the train speed

### ISSUE THREAD

**Issue by ztyxd** [mjq11302010044/RRPN_pytorch#14]
I use this code to train my own dataset, I used to use the facebook maskrcnn-benchmark and the speed is about 20 ours when traning 180000 iteration, but in this code , i train the rrpn with 

`MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 11
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 100000)
  MAX_ITER: 150000
  IMS_PER_BATCH: 2

OUTPUT_DIR: './models/XXX` 

It shows that it use smore than 2 days to finish the training phase

Is there something i ignored in the code or can U give me your training speed

Thanks a lot

**Comment by mjq11302010044** [comment]
@ztyxd I notice that your training batch is 2, while we use 1 in original training phase.

**Comment by ztyxd** [comment]
I will try， thanks a lot
