### ISSUE TITLE
about FPN and the assign of positive R-anchors

### ISSUE THREAD

**Issue by ztyxd** [mjq11302010044/RRPN_pytorch#15]
This is really a good work, but i still have some question?
First, can you give me some suggestions about use this model with FPN, i just replace the config with:
`MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 2000
    RPN_HEAD: "SingleConvRRPNHead"
  RRPN:
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 11
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DATA_train", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, 50000)
  MAX_ITER: 60000
  IMS_PER_BATCH: 1
OUTPUT_DIR: 'models/FPN/'
`
But the result seems to be bad compared with model without FPN

The second question is the assign about positive R-anchor, 
In the paper, you say:
`positive R-anchors feature the following: (i) the highest IoU overlap or an IoU larger than 0.7 with respect to the ground truth, and (ii) an intersection angle with respect to the ground truth of less than π/12.`

While in this code, it seems that just follow the first role about IOU and I cannot find the role about angle, may there is something I missed

Thanks

**Comment by mjq11302010044** [comment]
@ztyxd We finally found it better in IC15 without angle filtering, thus we didn't implement these conditions in pytorch version, more detail comparison may be investigated in the future. If you want these filtering codes, go and see it's caffe version in https://github.com/mjq11302010044/RRPN for more details.

**Comment by mjq11302010044** [comment]
@ztyxd About your FPN settings, the ANCHOR_SIZES may be wrong, one setting can be (2, 4, 8, 16, 32), which represents the times of 16 on rbox edges

**Comment by mjq11302010044** [comment]
@ztyxd Be careful to use FPN while your GPU memory less than 10G, the anchor matrix may be too large to place.

**Comment by ztyxd** [comment]
@mjq11302010044   Thank you for you reply I will check the CAFFE code, and Thank you for your suggestions about FPN configs

Thank YOU !!!!

**Comment by huazai-1994** [comment]
@ztyxd hey! have you find out the reason why the model with FPN has worse result? now I want to use the FPN, how should i set the configs to get a better result? Thanks !

**Comment by ztyxd** [comment]
@huazai-1994  I use the author's suggestion, the result have some improvement, but it still have a little decrease compared the model without FPN, maybe the problem is my dataset is too easy, the size in the dataset don‘t vary largely. You can use it in your own dataset and  remeber to follow the author the suggstions about configs

**Comment by huazai-1994** [comment]
@ztyxd Thank you very much for your reply!But I still have some problem while using the mutil_gpu whit the script 'python -m torch.distributed.launch --nproc_per_node=2 train_net.py --config-file "../configs/rrpn/e2e_rrpn_R_50_FPN_1x_ICDAR13_15_17_trial.yaml" ' . Then something wrong happened :RuntimeError: CUDA error: an illegal memory access was encountered terminate called without an active exception    
could you please give me som tips to fix it ? thanks

**Comment by clw5180** [comment]
> @mjq11302010044 @ztyxd Thank you very much for your reply!But I still have some problem while using the mutil_gpu with the script 'python -m torch.distributed.launch --nproc_per_node=2 train_net.py --config-file "../configs/rrpn/e2e_rrpn_R_50_FPN_1x_ICDAR13_15_17_trial.yaml" ' . Then something wrong happened :RuntimeError: CUDA error: an illegal memory access was encountered terminate called without an active exception
> could you please give me som tips to fix it ? thanks

请问这个问题你解决了么...

**Comment by clw5180** [comment]
> @huazai-1994 I use the author's suggestion, the result have some improvement, but it still have a little decrease compared the model without FPN, maybe the problem is my dataset is too easy, the size in the dataset don‘t vary largely. You can use it in your own dataset and remeber to follow the author the suggstions about configs

请问作者的意思是RRPN: ANCHOR_STRIDE: (2, 4, 8, 16, 32)么？ stride应该如何设置？

**Comment by clw5180** [comment]
> @huazai-1994 I use the author's suggestion, the result have some improvement, but it still have a little decrease compared the model without FPN, maybe the problem is my dataset is too easy, the size in the dataset don‘t vary largely. You can use it in your own dataset and remeber to follow the author the suggstions about configs

I try to use FPN, however I find that the use of GPU memory become less(~ 2000MB), and the training time becomes shorter than before(about only 4 hours), so how to deal with this problem? Thanks
