### ISSUE TITLE
KeyError: 'RRPN'

### ISSUE THREAD

**Issue by MiTeng0215** [mjq11302010044/RRPN_pytorch#20]
I followed the option1 of install.md file step by step. But now this problem has arisen, I don't know how to solve it, can you help me?

The following is Traceback
```
Traceback (most recent call last):
  File "tools/train_net.py", line 175, in <module>
    main()
  File "tools/train_net.py", line 168, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 30, in train
    model = build_detection_model(cfg)
  File "/home/y182235010/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 9, in build_detection_model
    meta_arch = _DETECTION_META_ARCHITECTURES[cfg.MODEL.META_ARCHITECTURE]
KeyError: 'RRPN'
(rrpn_pytorch) y182235010@node01:~/deeplearning/RRPN_ROOT$ 
```

**Comment by mjq11302010044** [comment]
@MiTeng0215 Are you sure you are using code in this repo or double check the code, this would not happen if you install our code in a correct way though.

**Comment by MiTeng0215** [comment]
> @MiTeng0215 Are you sure you are using code in this repo or double check the code, this would not happen if you install our code in a correct way though.

I am a new graduate student. I just follow your steps. I found a maskrcnn_benchmark file in your repository. In the readme file you asked me to install a maskrcnn_benchmark. Now the program is connected to `/github/maskrcnn_benchmark`, there is no RRPN in this connection, so the error happened. I don't know where I went wrong, my data set is downloaded from ICDAR official website.

**Comment by mjq11302010044** [comment]
@MiTeng0215  Okay, I find your problem, you should clone code from https://github.com/mjq11302010044/RRPN_pytorch.git first, then run the setup. I also update it in INSTALL.md. Hope that will help :)

**Comment by MiTeng0215** [comment]
> @MiTeng0215 Okay, I find your problem, you should clone code from https://github.com/mjq11302010044/RRPN_pytorch.git first, then run the setup. I also update it in INSTALL.md. Hope that will help :)

The problem is solved. I really appreciate you. Now the data is training.
```
Save pickle done.
DATASET: Total samples from: dict_keys(['IC15']) 930
2019-07-10 10:11:38,889 maskrcnn_benchmark.trainer INFO: Start training
```
