### ISSUE TITLE
想问下GT_BOX_MARGIN这个值是用来做什么的？另外如果使用FPN，为什么ANCHOR_SIZES: (2, 4, 8, 16, 32)

### ISSUE THREAD

**Issue by clw5180** [mjq11302010044/RRPN_pytorch#28]
FPN默认的anchor size不是32~512么，如果是2~32会不会太小了，难以检测比较大的物体？向大佬请教。

**Comment by ShaneYS** [comment]
你好，请问你知道GT_BOX_MARGIN这个参数是什么作用吗？为什么要把预测出的宽高除以这个值？

**Comment by lynesychen** [comment]
> 你好，请问你知道GT_BOX_MARGIN这个参数是什么作用吗？为什么要把预测出的宽高除以这个值？

可以参见论文《Arbitrary-Oriented Scene Text Detection via Rotation Proposals》的V.Experiments部分，其中的context of the text region，在transforms的randomRotation时候乘过gt_margin，为了让它带有图片上下文信息

**Comment by ShaneYS** [comment]
> 
> 
> > 你好，请问你知道GT_BOX_MARGIN这个参数是什么作用吗？为什么要把预测出的宽高除以这个值？
> 
> 可以参见论文《Arbitrary-Oriented Scene Text Detection via Rotation Proposals》的V.Experiments部分，其中的context of the text region，在transforms的randomRotation时候乘过gt_margin，为了让它带有图片上下文信息

感谢，明白了
