### ISSUE TITLE
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

### ISSUE THREAD

**Issue by bringBackm** [mjq11302010044/RRPN_pytorch#54]

**Comment by bringBackm** [comment]
Solved
Make sure you have the torch version 1.0.0.

**Comment by gdjmck** [comment]
Or you can just change the dtype of anchors in add_visibility_to() function in /modeling/rrpn/anchor_generator.py. It works for my pytorch 1.4 version and nan loss disappears.

**Comment by bringBackm** [comment]
@gdjmck 
Great!

**Comment by Pekary** [comment]
> Or you can just change the dtype of anchors in add_visibility_to() function in /modeling/rrpn/anchor_generator.py. It works for my pytorch 1.4 version and nan loss disappears.

 @gdjmck Hi, your method works when not using FPN, how to change the code avoiding this warning in FPN？

**Comment by gdjmck** [comment]
> > Or you can just change the dtype of anchors in add_visibility_to() function in /modeling/rrpn/anchor_generator.py. It works for my pytorch 1.4 version and nan loss disappears.
> 
> @gdjmck Hi, your method works when not using FPN, how to change the code avoiding this warning in FPN？I changed some `torch.uint8` in related files, but the warning still exists.

Maybe you can do something like below to raise the warning as exceptions to see which line of code causes the warning and deal with it.
>import warnings
>warnings.filterwarnings('error', 'xxx')

**Comment by Pekary** [comment]
@gdjmck ok, thanks!
