### ISSUE TITLE
could you share the pre-training weight for testing

### ISSUE THREAD

**Issue by yinianqingzhi** [mjq11302010044/RRPN_pytorch#7]
I just want to test the algorithm in my own data set,  so could you share the weight of the model.

**Comment by yinianqingzhi** [comment]
BaiduYun, Google Drive are both available, or can send to my mail jyzhang_2@stu.xidian.edu.cn. Thank you.

**Comment by zimenglan-sysu-512** [comment]
@mjq11302010044 
can u share some models that i can test the code after merging them into my framework?
thanks
